/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { Deal, DealCreate } from './dtos/Deal.dto';
import { DealController } from './Deal.controller';
import { DealService } from './Deal.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('DealController', () => {
  let controller: DealController;
  let spyService: DealService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: DealService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [DealController],
      providers: [DealService, ApiServiceProvider],
    }).compile();

    controller = module.get<DealController>(DealController);
    spyService = module.get<DealService>(DealService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call DealController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call DealController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new Deal();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
