/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Deal } from './Deal.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DealService } from './Deal.service';
import { DealController } from './Deal.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Deal])],
  providers: [DealService],
  exports: [DealService],
  controllers: [DealController],
})
export class DealModule {}
