/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Activity } from './Activity.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ActivityService } from './Activity.service';
import { ActivityController } from './Activity.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Activity])],
  providers: [ActivityService],
  exports: [ActivityService],
  controllers: [ActivityController],
})
export class ActivityModule {}
