import { ApiProperty } from '@nestjs/swagger';
/**
 * This file generated by Apso.
 */

export class ContactCreate {
  @ApiProperty()
  first_name: string;
  @ApiProperty()
  last_name: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  phone: string;
}

export class Contact {
  @ApiProperty()
  id: number;
  @ApiProperty()
  first_name: string;
  @ApiProperty()
  last_name: string;
  @ApiProperty()
  email: string;
  @ApiProperty()
  phone: string;
}
