/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Contact } from './Contact.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ContactService } from './Contact.service';
import { ContactController } from './Contact.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Contact])],
  providers: [ContactService],
  exports: [ContactService],
  controllers: [ContactController],
})
export class ContactModule {}
