/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { Note } from './Note.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { NoteService } from './Note.service';
import { NoteController } from './Note.controller';

@Module({
  imports: [TypeOrmModule.forFeature([Note])],
  providers: [NoteService],
  exports: [NoteService],
  controllers: [NoteController],
})
export class NoteModule {}
